#!/usr/bin/env bash
# Verify script for LSP-T-03 — exit code is the verdict. Generated by /pineapple:workorders.
set -uo pipefail
fail=0
run() { echo "▶ $*"; "$@"; rc=$?; echo "exit=$rc"; [ $rc -ne 0 ] && fail=1; }

PHASE_DOC=".pineapple/phases/v0.0.1-p2-onboarding-lsp.md"

run test -f "$PHASE_DOC"

# Must not have slipped lib/ fixes into this verification task — worker owns only the phase doc.
# (Presence of submitLsp is a dependency check, not an edit check.)
run bash -c 'grep -q "submitLsp" lib/features/onboarding/presentation/notifiers/signup_notifier.dart'
run bash -c '! grep -q "launchUrl" lib/features/onboarding/presentation/screens/signup_type_screen.dart'

# Smoke log bookkeeping present.
run bash -c "grep -q 'E2E smoke log (LSP-T-03)' \"$PHASE_DOC\""
run bash -c "grep -qE 'S1.*(pass|fail)' \"$PHASE_DOC\""
run bash -c "grep -qE 'S2.*(pass|fail)' \"$PHASE_DOC\""
run bash -c "grep -qE 'S7.*(pass|fail)' \"$PHASE_DOC\""

# If Done-when smoke box is checked, require all S1–S7 recorded as pass.
if grep -qE '^\s*-\s*\[[xX]\]\s*Manual E2E smoke' "$PHASE_DOC"; then
  run bash -c "grep -qE 'S1.*pass' \"$PHASE_DOC\""
  run bash -c "grep -qE 'S2.*pass' \"$PHASE_DOC\""
  run bash -c "grep -qE 'S3.*pass' \"$PHASE_DOC\""
  run bash -c "grep -qE 'S4.*pass' \"$PHASE_DOC\""
  run bash -c "grep -qE 'S5.*pass' \"$PHASE_DOC\""
  run bash -c "grep -qE 'S6.*pass' \"$PHASE_DOC\""
  run bash -c "grep -qE 'S7.*pass' \"$PHASE_DOC\""
else
  echo "▶ (Done-when smoke box unchecked — allowing fail log without full pass set)"
fi

exit $fail
