#!/usr/bin/env bash
# Verify script for LSP-T-02 — exit code is the verdict. Generated by /pineapple:workorders.
set -uo pipefail
fail=0
run() { echo "▶ $*"; "$@"; rc=$?; echo "exit=$rc"; [ $rc -ne 0 ] && fail=1; }

# Dependency: LSP-T-01 wire must be present.
run bash -c 'grep -q "signupLsp" lib/core/auth/data/auth_repository.dart'
run bash -c 'grep -qE "^\s*lsp,?\s*$" lib/core/auth/domain/email_verification.dart'

run test -f lib/features/onboarding/presentation/screens/signup_type_screen.dart
run test -f lib/features/onboarding/presentation/screens/signup_details_screen.dart
run test -f lib/features/onboarding/presentation/notifiers/signup_notifier.dart
run test -f lib/features/onboarding/l10n/onboarding_strings.dart

# Type screen: no external launch for LSP.
run bash -c '! grep -q "launchUrl" lib/features/onboarding/presentation/screens/signup_type_screen.dart'
run bash -c '! grep -q "url_launcher" lib/features/onboarding/presentation/screens/signup_type_screen.dart'
run bash -c '! grep -q "webAdminBaseUrl" lib/features/onboarding/presentation/screens/signup_type_screen.dart'
run bash -c 'grep -q "SignupPath.lsp" lib/features/onboarding/presentation/screens/signup_type_screen.dart'
run bash -c 'grep -q "SignupDraft" lib/features/onboarding/presentation/screens/signup_type_screen.dart'

# Notifier: submitLsp → signupLsp; no new error-code branches for LSP.
run bash -c 'grep -q "submitLsp" lib/features/onboarding/presentation/notifiers/signup_notifier.dart'
run bash -c 'grep -q "_repo.signupLsp\|signupLsp(" lib/features/onboarding/presentation/notifiers/signup_notifier.dart'
run bash -c 'grep -q "SignupPath.lsp" lib/features/onboarding/presentation/notifiers/signup_notifier.dart'
run bash -c '! grep -qE "EMAIL_ALREADY_EXISTS|CONSENT_REQUIRED" lib/features/onboarding/presentation/notifiers/signup_notifier.dart'

# Details: LSP fields + baa gate + submitLsp call.
run bash -c 'grep -q "SignupPath.lsp" lib/features/onboarding/presentation/screens/signup_details_screen.dart'
run bash -c 'grep -q "submitLsp" lib/features/onboarding/presentation/screens/signup_details_screen.dart'
run bash -c 'grep -q "_baaAck\|baaAck" lib/features/onboarding/presentation/screens/signup_details_screen.dart'
run bash -c 'grep -q "acceptBaa\|OnboardingStrings.acceptBaa" lib/features/onboarding/presentation/screens/signup_details_screen.dart'

# Strings present.
run bash -c 'grep -q "acceptBaa" lib/features/onboarding/l10n/onboarding_strings.dart'
run bash -c 'grep -q "detailsSubLsp" lib/features/onboarding/l10n/onboarding_strings.dart'

run flutter analyze \
  lib/features/onboarding/presentation/screens/signup_type_screen.dart \
  lib/features/onboarding/presentation/screens/signup_details_screen.dart \
  lib/features/onboarding/presentation/notifiers/signup_notifier.dart \
  lib/features/onboarding/l10n/onboarding_strings.dart

exit $fail
