#!/usr/bin/env bash
# Verify script for LSP-T-01 — exit code is the verdict. Generated by /pineapple:workorders.
set -uo pipefail
fail=0
run() { echo "▶ $*"; "$@"; rc=$?; echo "exit=$rc"; [ $rc -ne 0 ] && fail=1; }

run test -f lib/core/auth/domain/email_verification.dart
run test -f lib/core/auth/data/dto/auth_dto.dart
run test -f lib/core/auth/data/auth_repository.dart
run test -f lib/features/onboarding/presentation/routes/onboarding_routes.dart

run bash -c 'grep -qE "^\s*lsp,?\s*$" lib/core/auth/domain/email_verification.dart'
run bash -c 'grep -q "SignupPath.lsp" lib/core/auth/domain/email_verification.dart'
run bash -c 'grep -qE "SignupLspRequestDto" lib/core/auth/data/dto/auth_dto.dart'
run bash -c 'grep -qE "@Default\('\''lsp'\''\)|business_type.*lsp|@Default\(\"lsp\"\)" lib/core/auth/data/dto/auth_dto.dart'
run bash -c 'grep -q "signupLsp" lib/core/auth/data/auth_repository.dart'
run bash -c 'grep -q "SignupLspRequestDto" lib/core/auth/data/auth_repository.dart'
run bash -c 'grep -q "baaAck" lib/core/auth/data/auth_repository.dart'
run bash -c 'grep -q "SignupPath.lsp" lib/features/onboarding/presentation/routes/onboarding_routes.dart'
run bash -c 'grep -qE "'\''lsp'\''" lib/features/onboarding/presentation/routes/onboarding_routes.dart'

run flutter analyze \
  lib/core/auth/domain/email_verification.dart \
  lib/core/auth/data/dto/auth_dto.dart \
  lib/core/auth/data/auth_repository.dart \
  lib/features/onboarding/presentation/routes/onboarding_routes.dart

exit $fail
